# Generated by Django 4.1.3 on 2022-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_description', models.TextField()),
                ('release_date', models.DateField()),
                ('movie_duration', models.CharField(max_length=100)),
            ],
        ),
    ]
